[features]
seeds = false
skip-lint = false
[programs.localnet]
hubkon_solana_contracts = "GjKqR2iWys9dR9EwBdFS5QYDFt6NZAbGD65j2JENHTSs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/filipe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "1.1.2"
